version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=users
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=concert
      - TZ= Asia/Seoul
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

networks:
  default:
    driver: bridge
