version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=users
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=concert
      - TZ= Asia/Seoul
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - default
  redis-container:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    command: [ "redis-server" ]
    volumes:
      - ./data/redis:/data
      - ./data/redis/conf:/usr/local/conf/redis.conf
    networks:
      - default


networks:
  default:
    driver: bridge
